server:
  port: 8100

spring:
  # 数据库配置
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/langchat?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      keep-alive: true

  # Redis配置
  data:
    redis:
      port: 6379
      host: 127.0.0.1
      database: 1
      jedis:
        pool:
          max-wait: 2000
          time-between-eviction-runs: 1000

langchat:
  auth:
    email:
      host: smtp.qq.com
      port: 465
      from: <EMAIL>
      pass: <PASS>
  vectorstore:
    pgvector:
      host: 127.0.0.1
      user: root
      password: root
      port: 5432
      database: langchat
      table: vector_1
      dimension: 384
  web-search:
    google:
      api-key: <KEY>
      csi: <CSI>

