# Compose a postgres database together with the extension pgvector
services:
  db:
    hostname: db
    image: registry.cn-beijing.aliyuncs.com/langchat/pgvector
    ports:
     - 5432:5432
    restart: always
    environment:
      - POSTGRES_DB=vectordb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    #  - ./init.sql:/docker-entrypoint-initdb.d/init.sql
