version: "3"

services:
  langchat-client:
    image: registry.cn-beijing.aliyuncs.com/langchat/langchat-client
    restart: always
    ports:
      - 3011:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - langchat-net

networks:
  langchat-net:
    driver: bridge
