version: "3"

services:
  langchat:
    image: registry.cn-beijing.aliyuncs.com/langchat/langchat
    restart: always
    ports:
      - 8100:8100
    environment:
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=12345678
      - SPRING_DATASOURCE_URL=jdbc:mysql://127.0.0.1:3306/langchat?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_DATA_REDIS_HOST=127.0.0.1
      - SPRING_DATA_REDIS_DATABASE=1
      - LANGCHAT_VECTORSTORE_PGVECTOR_HOST=127.0.0.1
      - LANGCHAT_VECTORSTORE_PGVECTOR_USER=root
      - LANGCHAT_VECTORSTORE_PGVECTOR_PASSWORD=root
      - LANGCHAT_VECTORSTORE_PGVECTOR_PORT=5432
      - LANGCHAT_VECTORSTORE_PGVECTOR_DATABASE=langchat
      - LANGCHAT_VECTORSTORE_PGVECTOR_TABLE=vector_1
      - LANGCHAT_VECTORSTORE_PGVECTOR_DIMENSION=384
    volumes:
      - ./logs/:/app/logs
    networks:
      - langchat-net

networks:
  langchat-net:
    driver: bridge